#[derive(Debug)]
pub enum InputLanguage {
    Automatic,
    Defined(Language),
}

#[derive(Debug)]
pub enum Language {
    Afrikaans,
    Albanian,
    Amharic,
    Arabic,
    Armenian,
    Azerbaijan,
    Bashkir,
    Basque,
    Belarusian,
    Bengali,
    Bosnian,
    Bulgarian,
    Burmese,
    Catalan,
    Cebuano,
    Chinese,
    Croatian,
    Czech,
    Danish,
    Dutch,
    English,
    Esperanto,
    Estonian,
    Finnish,
    French,
    Galician,
    Georgian,
    German,
    Greek,
    Gujarati,
    HaitianCreole,
    Hebrew,
    HillMari,
    Hindi,
    Hungarian,
    Icelandic,
    Indonesian,
    Irish,
    Italian,
    Japanese,
    Javanese,
    Kannada,
    Kazakh,
    Khmer,
    Korean,
    Kyrgyz,
    Laotian,
    Latin,
    Latvian,
    Lithuanian,
    Luxembourgish,
    Macedonian,
    Malagasy,
    Malay,
    Malayalam,
    Maltese,
    Maori,
    Marathi,
    Mari,
    Mongolian,
    Nepali,
    Norwegian,
    Papiamento,
    Persian,
    Polish,
    Portuguese,
    Punjabi,
    Romanian,
    Russian,
    Scottish,
    Serbian,
    Sinhala,
    Slovakian,
    Slovenian,
    Spanish,
    Sundanese,
    Swahili,
    Swedish,
    Tagalog,
    Tajik,
    Tamil,
    Tatar,
    Telugu,
    Thai,
    Turkish,
    Udmurt,
    Ukrainian,
    Urdu,
    Uzbek,
    Vietnamese,
    Welsh,
    Xhosa,
    Yiddish,
}

impl Language {
    pub fn to_language_code(&self) -> &'static str {
        use Language::*;
        match *self {
            // YANDEX api-compatibles
            Afrikaans => "af",
            Albanian => "sq",
            Amharic => "am",
            Arabic => "ar",
            Armenian => "hy",
            Azerbaijan => "az",
            Bashkir => "ba",
            Basque => "eu",
            Belarusian => "be",
            Bengali => "bn",
            Bosnian => "bs",
            Bulgarian => "bg",
            Burmese => "my",
            Catalan => "ca",
            Cebuano => "ceb",
            Chinese => "zh",
            Croatian => "hr",
            Czech => "cs",
            Danish => "da",
            Dutch => "nl",
            English => "en",
            Esperanto => "eo",
            Estonian => "et",
            Finnish => "fi",
            French => "fr",
            Galician => "gl",
            Georgian => "ka",
            German => "de",
            Greek => "el",
            Gujarati => "gu",
            HaitianCreole => "ht",
            Hebrew => "he",
            HillMari => "mrj",
            Hindi => "hi",
            Hungarian => "hu",
            Icelandic => "is",
            Indonesian => "id",
            Irish => "ga",
            Italian => "it",
            Japanese => "ja",
            Javanese => "jv",
            Kannada => "kn",
            Kazakh => "kk",
            Khmer => "km",
            Korean => "ko",
            Kyrgyz => "ky",
            Laotian => "lo",
            Latin => "la",
            Latvian => "lv",
            Lithuanian => "lt",
            Luxembourgish => "lb",
            Macedonian => "mk",
            Malagasy => "mg",
            Malay => "ms",
            Malayalam => "ml",
            Maltese => "mt",
            Maori => "mi",
            Marathi => "mr",
            Mari => "mhr",
            Mongolian => "mn",
            Nepali => "ne",
            Norwegian => "no",
            Papiamento => "pap",
            Persian => "fa",
            Polish => "pl",
            Portuguese => "pt",
            Punjabi => "pa",
            Romanian => "ro",
            Russian => "ru",
            Scottish => "gd",
            Serbian => "sr",
            Sinhala => "si",
            Slovakian => "sk",
            Slovenian => "sl",
            Spanish => "es",
            Sundanese => "su",
            Swahili => "sw",
            Swedish => "sv",
            Tagalog => "tl",
            Tajik => "tg",
            Tamil => "ta",
            Tatar => "tt",
            Telugu => "te",
            Thai => "th",
            Turkish => "tr",
            Udmurt => "udm",
            Ukrainian => "uk",
            Urdu => "ur",
            Uzbek => "uz",
            Vietnamese => "vi",
            Welsh => "cy",
            Xhosa => "xh",
            Yiddish => "yi",
        }
    }
}
